<?php

use application\Session;

function selected($value, $selected) {
    return $value == $selected ? ' selected="selected"' : '';
}
?>
<div id="wrap">

    <!-- Header
    ================================================== -->
    <div id="nav-bar" style="margin-left: 180px; ">
        <div class="pull-left">
            <div id="header-container">

                <div class="dropdown"         style="">
                    <a class="header-dropdown dropdown-toggle accent-color" data-toggle="dropdown" href="#" style="color: white; ">
                       <?php if(isset($this->titulo)): echo $this->titulo; endif;?>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo URL . "matricula" . DS1 . "index/" ?>">Matriculas</a></li>
                        <li><a href="<?php echo URL . "docente" . DS1 . "index/" ?>">Docentes</a></li>
                        <li><a href="<?php echo URL . "curso" . DS1 . "index/" ?>">Cursos</a></li>
                        <li><a href="<?php echo URL . "modulo" . DS1 . "index/" ?>">Módulos</a></li>
                        <li><a href="<?php echo URL . "nota" . DS1 . "listar/" ?>">Notas</a></li>
                        <li><a href="<?php echo URL . "relatorio" . DS1 . "graficoGeral/" ?>">Relatório</a></li>
                        <li><a href="<?php echo URL . "diploma" . DS1 . "index/" ?>">Diplomas</a></li>
                        <li><a href="<?php echo URL . "certificado" . DS1 . "index/" ?>">Certificado</a></li>
                        <li><a href="<?php echo URL . "programa" . DS1 . "index/" ?>">Programa</a></li>
                        <li><a href="<?php echo URL . "usuario" . DS1 . "index/" ?>">Usuarios</a></li>
                        <li><a href="<?php echo URL . "login/logof"; ?>">Sair</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="pull-right">
            <div id="top-info" class="pull-right">
                <a id="settings" href="#" class="win-command pull-right">
                    <span class="win-commandicon win-commandring icon-cog-3"></span>
                </a>
                <a id="logged-user" href="#" class="win-command pull-right">
                    <span class="win-commandicon win-commandring icon-user"></span>
                </a>
                <div class="pull-right" style="margin-right:150px; ">
                    <h3><?php echo application\Session::get('nome'); ?></h3>
                    <a href="<?php echo URL . "login/logof"; ?>"><h4 class="text-warning pull-right">Sair</h4></a>
                </div>
            </div>
        </div>
    </div>


    <div class="metro panorama" style="margin-left: 220px;">
        <div class="panorama-sections">

            <div class="panorama-section">

                <h2>Matriculas</h2>


                <div class="tile-column-span-2">
                    <a class="tile wide imagetext wideimage bg-color-blue" href="<?php echo URL . "matricula" . DS1 . "index/" ?>">
                        <img src="<?php echo URL; ?>public/img/img3.png" alt="sam" style="width:200px;" />
                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">Adicionar, Alterar, Apagar, Alunos</div>
                        </div>
                    </a>
                    <h2>Cursos</h2>

                    <a class="tile wide imagetext wideimage bg-color-purple" href="<?php echo URL . "curso" . DS1 . "index/" ?>">
                        <img src="<?php echo URL; ?>public/img/img7.png" alt="sam" style="width:200px;" />
                        <div class="textover-wrapper bg-color-purple">
                            <div class="text2">Adicionar, Alterar, Apagar, Curso</div>
                        </div>
                    </a>
                    <h2>Módulos</h2>

                    <a class="tile wide imagetext wideimage bg-color-blue" href="<?php echo URL . "modulo" . DS1 . "index/" ?>">
                        <img src="<?php echo URL; ?>public/img/img8.png" alt="sam" style="width:200px;" />
                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">Adicionar, Alterar, Apagar, Modulos</div>
                        </div>
                    </a>


                </div>



            </div>



            <div class="panorama-section">

                <h2>Docentes</h2>

                <div class="tile-column-span-2">


                    <a class="tile wide imagetext wideimage " href="<?php echo URL . "docente" . DS1 . "index/" ?>" style="background-color:white;">
                        <img src="<?php echo URL; ?>public/img/img6.png" alt="sam"  style="width:200px;"/>

                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">Adicionar, Alterar, Apagar</div>
                        </div>
                    </a>

                </div>


                <h2>Notas</h2>

                <div class="tile-column-span-2">


                    <a class="tile wide imagetext wideimage" href="<?php echo URL . "nota" . DS1 . "listar/" ?>" style="background-color:white;">
                        <img src="<?php echo URL; ?>public/img/img9.png" alt="sam"  style="width:200px;"/>

                        <div class="textover-wrapper bg-color-red">
                            <div class="text2">Adicionar, Alterar, Apagar</div>
                        </div>
                    </a>

                </div>


                <h2>Programa de Estudo</h2>

                <div class="tile-column-span-2">


                    <a class="tile wide imagetext wideimage" href="<?php echo URL . "programa" . DS1 . "index/" ?>" style="background-color:white;">
                        <img src="<?php echo URL; ?>public/img/img10.png" alt="sam"  style="width:200px;"/>

                        <div class="textover-wrapper bg-color-blueDark">
                            <div class="text2">Adicionar, Alterar, Apagar</div>
                        </div>
                    </a>

                </div>









            </div> 

            <div class="panorama-section tile-span-4">
                <h2>Documentos</h2>


                <a class="tile wide imagetext bg-color-grayLight" href="<?php echo URL . "relatorio" . DS1 . "graficoGeral/" ?>">
                    <div class="image-wrapper">
                        <img src="<?php echo URL; ?>public/img/img4.png" alt="sam"  class="img-responsive img-rounded" />
                    </div>
                    <div class="column-text">
                        <div class="text4">Imprimir Relatorios</div>
                    </div>
                </a>






                <a class="tile app bg-color-blue" href="<?php echo URL . "certificado" . DS1 . "index/" ?>">
                    <div class="image-wrapper">
                        <img src="<?php echo URL; ?>public/img/img11.png" alt="sam"  style="width:400px"; height="400px;" />
                    </div>
                    <div class="column-text" style="color:black; fonte-size:14px;">
                        <div class="text4">Imprimir Certificados</div>
                    </div>
                </a>


                <a class="tile wide imagetext bg-color-yellow" href="<?php echo URL . "diploma" . DS1 . "index/" ?>">
                    <div class="image-wrapper">
                        <img src="<?php echo URL; ?>public/img/img11.png" alt="sam"  style="width:400px"; height="400px;" />
                    </div>
                    <div class="column-text" style="color:black; fonte-size:14px;">
                        <div class="text4">Imprimir Diplomas</div>
                    </div>
                </a>






                <div id="charms" class="win-ui-dark slide">

                    <div id="theme-charms-section" class="charms-section">
                        <div class="charms-header">
                            <a href="#" class="close-charms win-backbutton"></a>
                            <h2>Definições</h2>
                        </div>

                        <div class="row-fluid">
                            <div class="span12">
                                <form action="dashboard/alteraTema" id="tema">
                                    <label for="win-theme-select">Alterar Tema:</label>
                                    <select id="win-theme-select" class="tema" name="tema">

                                        <option value="default" <?php echo selected(Session::get('tema'), "default") ?> >Default</option>
                                        <option value="metro" <?php echo selected(Session::get('tema'), "metro") ?> >Metro</option>
                                    </select>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div id="charms" class="win-ui-dark slide">

                <div id="theme-charms-section" class="charms-section">
                    <div class="charms-header">
                        <a href="#" class="close-charms win-backbutton"></a>
                        <h2>Definições</h2>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <form action="dashboard/alteraTema" id="tema">
                                <label for="win-theme-select">Alterar Tema:</label>
                                <select id="win-theme-select" class="tema" name="tema">

                                    <option value="default" <?php echo selected(Session::get('tema'), "default") ?> >Default</option>
                                    <option value="metro" <?php echo selected(Session::get('tema'), "metro") ?> >Metro</option>
                                </select>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>



	<?php echo $this->menuVertical; ?>


