
            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>
                    <tr class="odd gradeA">


                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>Grau</th>
                        <th>Modulo</th>

                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados['bi']; ?></td>
                                <td><a href="#" onclick="modal(<?php echo $dados['docente']; ?>);"><?php print $dados['nome']; ?></a></td>
                                <td><?php print $dados['grau']; ?></td>
                                 <td><?php print $dados['nome_modulo']; ?></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>


<div class="bs-example">
    <!-- Button HTML (to Trigger Modal) -->

    <!-- Modal HTML -->
    <div id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Informação</h4>
                </div>
                <div class="modal-body">
                    <h3>Informação do docente</h3>
                    <div>
                        <h4>Modulos Inscritos: </h4>
                        <div id="conteudo"></div>
                    </div>                    
                </div>
                <div class="modal-footer">
                    <a class="btn btn-default" data-dismiss="modal" href="<?php echo URL . "docente"; ?>" data-remote="<?php echo URL . "docente"; ?>" rel="0" id="fechar">Fechar</a>
                </div>
            </div>
        </div>
    </div>
</div>