<?php echo $this->menu; ?>

<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">
    <h3></h3>
    <div class="navbar">
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "nota" . DS1 . "index/" ?>"class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Lançar Nota</span></a></li>
            <li class="active"><a href="<?php echo URL . "nota" . DS1 . "editar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Editar</span></a></li>
            <li class="active"><a href="<?php echo URL . "nota" . DS1 . "remover/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Apagar</span></a></li>
        </ul>
    </div>


</div>

<div  id="content" style="margin-left: 120px; ">
    <div class="row-fluid">

        <div class="block">





            <div class="span6 " id="content" style="margin-left: 150px; margin-top: 50px;">
                <!-- validation -->

                <div class="row-fluid">

                    <!-- block -->
                    <div class="block">




                        <div class="block-content collapse in">
                            <div class="span12">

                            <form class="form-horizontal">
                                <fieldset>
                                    <legend class="text-info text-center">Selecciona os dados a pesquisar</legend>
                                    <div class="control-group">
                                        <label class="control-label">Ano<span class="required">*</span></label>


                                        <div class="controls">
                                            <input type="text" name="ano"  class="span6 m-wrap" id="ano"/>


                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label">Curso<span class="required">*</span></label>
                                        <div class="controls">
                                            <select id="curso" class="span6 m-wrap">
                                                <option value="">- Curso -</option>

                                            </select>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label">Modúlo<span class="required">*</span></label>
                                        <div class="controls">
                                            <select id="modulo" class="span6 m-wrap">
                                                <option value="">- Modulo -</option>

                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-actions">
                                        <input type="button" name="btnPesquisar" value="Pesquisar" id="buscar"  class="btn btn-success"  onclick="getDados('buscar');"/>
                                        <input type="button" name="btnPesquisar" value="Carregar Todos" id="buscar" class="btn btn-primary" onclick="getTodos('buscar');" />
                                        <input type="hidden" value="<?php echo URL; ?>public/img/6.gif" id="img"/>
                                    </div>
                                </fieldset>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
            <h3 style="position: absolute; right: 600px;">  <?php
                if (isset($this->titulo)): echo $this->titulo;
                endif;
                ?> </h3>

        </div>

    </div>

</div>



<div id="conteudo">

</div>




