

<?php echo $this->menu; ?>


<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">
    <h3></h3>
    <div class="navbar">
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "nota" . DS1 . "index/" ?>"class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Lançar Nota</span></a></li>
            <li class="active"><a href="<?php echo URL . "nota" . DS1 . "editar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Editar</span></a></li>
            <li class="active"><a href="<?php echo URL . "nota" . DS1 . "remover/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Apagar</span></a></li>
        </ul>
    </div>


</div>

<div class="span11 " id="content" style="margin-left: 150px; " >
    <div class="row-fluid">
        <div class="block">




            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>

                    <tr class="odd gradeA">

                        <th>Nª BI</th> 
                        <th>Nome</th>
                        <th>Nota</th>
                        <th>Apagar</th>
                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getAluno()->getPessoa()->getBi(); ?></td>
                                <td><?php print $dados->getAluno()->getPessoa()->getNome(); ?></td>
                                <td><?php echo $dados->getNota(); ?></td>
                                <td>            
                                    <form action="<?php print URL; ?>nota/remover"   method="POST">            

                                        <input name="enviar" type="hidden" value="1"/>
                                        <input type="hidden" name="id" value="<?php print $dados->getId(); ?>"/>
                                        <input name="button" type="submit" class="input" id="button" value="Apagar"/>
                                    </form>
                                </td>

                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>





