<?php echo $this->menu;?>
<div class="span10 " id="content" style="margin-left: 150px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
        <div class="navbar navbar-inner block-header" style="margin-top: 20px;">
            <div class="muted pull-left" style="padding: 10px; color: blue;">Suas definições<?php
                if (isset($this->titulo)): print $this->titulo;
					endif;
				?>
			</div>
        </div>
        <div class="block-content collapse in">
            <div class="span12">

                <table  class="table table-striped table-bordered">   
                    <thead>
                        <tr>
                            <th>Nome</th> 
                            <th>Login</th>
                             <th>Senha</th>
                            <th>Alterar</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php if (isset($this->dados) && !empty($this->dados)): $dados = $this->dados; ?>


                            <tr>
                                <td><?php print $dados->getPessoa()->getNome(); ?></td>
                                <td><?php print $dados->getLogin(); ?></td>
                                <td>*********</td>
                                <td><a href="<?php echo URL."aluno/alteraSenha";?>">Alterar</a></td>
                            </tr>

                        </tbody>
                    </table>
                <?php else: ?>
                    <h2 class="text-center text-error">Dados não encontrado</h2>
                <?php endif; ?>
               
            </div>
        </div>
    </div>
    <!-- /block -->
</div>
</div>