

<?php use application\Session;?>  





<div class="span10 " id="content" style="margin-left: 15px; margin-top: 100px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
          
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>aluno/pesquisaPor" id="buscar" class="form-horizontal" method="POST" >
                        <fieldset>
                            <legend class="text-info" style="margin-left: 180px;">Selecciona os dados a pesquisar</legend>
                            <div class="control-group">
                                <label class="control-label">Curso<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap " id="curso" name="curso">
                                        <option value="000">-Selecciona um curso-</option>
                                    </select>


                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Modúlo<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap" id="modulo" name="modulo">
                                        <option value="000">-Seleciona um modulo-</option>
                                    </select>


                                </div>
                            </div>
                        </fieldset>

                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="buscar">Procurar</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>




<br />

<?php if (isset($this->dados) && !empty($this->dados)): ?>


         
<div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <?php if (Session::get('nivel') == "administrador"): ?>
                        <a class="brand" href="#">Painel de Administração</a>
                    <?php endif; ?>

                    <?php if (Session::get('nivel') == "docente"): ?>
                        <a class="brand" href="#">Painel de Docente</a>
                    <?php endif; ?>

                    <?php if (Session::get('nivel') == "aluno"): ?>
                        <a class="brand" href="#">Painel de Aluno</a>
                    <?php endif; ?>

                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"> <i class="icon-user"></i> <?php print Session::get('nome'); ?> <i class="caret"></i>

                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a tabindex="-1" href="<?php echo URL . "matricula" . DS1 . "informacao/" . Session::get('id'); ?>">Perfil</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a tabindex="-1" href="<?php print URL ?>login/logof">Sair</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>

                        <ul class="nav">
                            <?php if (Session::get('nivel') == "administrador"): ?>
                                <li class="active">
                                    <a href="<?php print URL ?>dashboard">Dashboard</a>
                                </li>
                            <?php endif; ?>

                            <?php if (Session::get('nivel') == "docente"): ?>
                                <li class="active">
                                    <a href="<?php print URL ?>dashboard/docente">Dashboard</a>
                                </li>
                            <?php endif; ?>

                            <?php if (Session::get('nivel') == "aluno"): ?>
                                <li class="active">
                                    <a href="<?php print URL ?>dashboard/aluno">Dashboard</a>
                                </li>
                            <?php endif; ?>


                            <?php if (isset($_layoutParam["menu"])): ?>
                                <?php for ($i = 0; $i < count($_layoutParam["menu"]); $i++): ?>
                                    <?php (($item && $_layoutParam["menu"][$i]["id"] == $item) ? $item_style = "corrent" : $item_style = ""); ?> 

                                    <li class="active" id="<?php print $item_style; ?>"><a href="<?php echo $_layoutParam["menu"][$i]["link"]; ?>"><i class="icon-chevron-right"></i> <?php echo $_layoutParam["menu"][$i]["titulo"]; ?></a></li>
                                    <?php
                                endfor;
                            endif;
                            ?>

                        </ul>
                    </div>
                </div>
            </div>
        </div>

//fim da barra de menu














    <div class="span10 " id="content" style="margin-left: 300px;">
        <!-- validation -->
        <div class="row-fluid">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left text-success">Dados Encontrados</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">

                        <table  class="table table-striped table-bordered">   
                            <thead>
                                <tr>

                                    <th>CURSO</th> 
                                    <th>MODÚLO</th>
                                    <th>DOCENTE</th>
                                    <th>NOME</th>
                                    <th>DATA</th>

                                </tr>
                            </thead>

                            <tbody>

                                <?php if (isset($this->dados) && !empty($this->dados)): ?>
                                    <?php foreach ($this->dados as $dados): ?>
                                        <tr>
                                            <td><?php print $dados->getCurso()->getNome(); ?></td>
                                            <td><?php print $dados->getModulo()->getNome(); ?></td>
                                            <td><?php print $dados->getDocente()->getPessoa()->getNome(); ?></td>
                                            <td><?php print "{" . $dados->getNome() . "}"; ?><a href="<?php print URL . $dados->getNome(); ?>" target="_BLANK">     (VER)</a></td>
                                            <td><?php print $dados->getData(); ?></td>
                                        </tr>

                                        <?php
                                    endforeach;
                                endif;
                                ?>

                            </tbody>
                        </table>



                    </div>
                </div>
            </div>
        </div>
    </div>

<?php endif; ?>


