<?php

namespace DoctrineProxies\__CG__\models;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Aluno extends \models\Aluno implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'models\\Aluno' . "\0" . 'id', '' . "\0" . 'models\\Aluno' . "\0" . 'graduacao', '' . "\0" . 'models\\Aluno' . "\0" . 'universidade', '' . "\0" . 'models\\Aluno' . "\0" . 'unidadeOrganica', '' . "\0" . 'models\\Aluno' . "\0" . 'categoriaDocente', '' . "\0" . 'models\\Aluno' . "\0" . 'funcao', '' . "\0" . 'models\\Aluno' . "\0" . 'categoriaCientifica', '' . "\0" . 'models\\Aluno' . "\0" . 'pessoa');
        }

        return array('__isInitialized__', '' . "\0" . 'models\\Aluno' . "\0" . 'id', '' . "\0" . 'models\\Aluno' . "\0" . 'graduacao', '' . "\0" . 'models\\Aluno' . "\0" . 'universidade', '' . "\0" . 'models\\Aluno' . "\0" . 'unidadeOrganica', '' . "\0" . 'models\\Aluno' . "\0" . 'categoriaDocente', '' . "\0" . 'models\\Aluno' . "\0" . 'funcao', '' . "\0" . 'models\\Aluno' . "\0" . 'categoriaCientifica', '' . "\0" . 'models\\Aluno' . "\0" . 'pessoa');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Aluno $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }
    
    
       
 

    /**
     * {@inheritDoc}
     */
    public function getGraduacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGraduacao', array());

        return parent::getGraduacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getUniversidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniversidade', array());

        return parent::getUniversidade();
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadeOrganica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadeOrganica', array());

        return parent::getUnidadeOrganica();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriaDocente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriaDocente', array());

        return parent::getCategoriaDocente();
    }

    /**
     * {@inheritDoc}
     */
    public function getFuncao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuncao', array());

        return parent::getFuncao();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriaCientifica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriaCientifica', array());

        return parent::getCategoriaCientifica();
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoa', array());

        return parent::getPessoa();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setGraduacao($graduacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGraduacao', array($graduacao));

        return parent::setGraduacao($graduacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setUniversidade($universidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniversidade', array($universidade));

        return parent::setUniversidade($universidade);
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadeOrganica($unidadeOrganica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadeOrganica', array($unidadeOrganica));

        return parent::setUnidadeOrganica($unidadeOrganica);
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoriaDocente($categoriaDocente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoriaDocente', array($categoriaDocente));

        return parent::setCategoriaDocente($categoriaDocente);
    }

    /**
     * {@inheritDoc}
     */
    public function setFuncao($funcao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuncao', array($funcao));

        return parent::setFuncao($funcao);
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoriaCientifica($categoriaCientifica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoriaCientifica', array($categoriaCientifica));

        return parent::setCategoriaCientifica($categoriaCientifica);
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoa(\models\Pessoa $pessoa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoa', array($pessoa));

        return parent::setPessoa($pessoa);
    }

    /**
     * {@inheritDoc}
     */
    public function adicionar($dados = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'adicionar', array($dados));

        return parent::adicionar($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function adiciona($dados, $id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'adiciona', array($dados, $id));

        return parent::adiciona($dados, $id);
    }

    /**
     * {@inheritDoc}
     */
    public function editar($id = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'editar', array($id));

        return parent::editar($id);
    }

    /**
     * {@inheritDoc}
     */
    public function pesquisaPor($dados = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'pesquisaPor', array($dados));

        return parent::pesquisaPor($dados);
    }

    /**
     * {@inheritDoc}
     */
    public function pesquisar($id = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'pesquisar', array($id));

        return parent::pesquisar($id);
    }

    /**
     * {@inheritDoc}
     */
    public function remover($id = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remover', array($id));

        return parent::remover($id);
    }

}
