
<div class="span10 " id="content" style="margin-left: 220px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <table  class="table table-striped table-bordered">   
                <thead>
                    <tr>

                        <th>CURSO</th> 
                        <th>MODÚLO</th>
                        <th>DOCENTE</th>
                        <th>LOCAL</th>
                        <th>INICIO</th>
                        <th>TERMINA</th>
                        <th>HORAS</th>
                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getCurso()->getNome(); ?></td>
                                <td><?php print $dados->getModulo()->getNome(); ?></td>
                                <td><?php print $dados->getDocente()->getPessoa()->getNome(); ?></td>
                                <td><?php print $dados->getLocal(); ?></td>
                                <td><?php print $dados->getData(); ?></td>
                                <td><?php print $dados->getDatafinal(); ?></td>
                                <td><?php print $dados->getHoras(); ?></td>
                                <td><a href="#" id="editar1" rel="<?php echo $dados->getId(); ?>"><i class="icon-edit"></i></a></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>
        </div>
    </div>
</div>


