<?php echo $this->menu; ?>
<div class=" " id="content" style="margin-left: 120px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->

        <div class="block">
           
            <?php if(strcmp(application\Session::get('nivel'), 'docente') == 0):?>
            <div class="col-12 pull-left">

                <h3></h3>
                <div class="navbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo URL . "materia" . DS1 . "adicionar1/" ?>"><span style="font-size: 14px; color: black;">Cadastrar</span></a></li>
                    </ul>
                </div>


            </div>
            <?php endif;?>
            <table  class="table table-striped table-bordered" id="tabela">   
                <thead>
                    <tr class="odd gradeA">

                        <th>CURSO</th> 
                        <th>MODÚLO</th>
                        <th>DOCENTE</th>
                        <th>NOME</th>
                        <th>DATA</th>

                    </tr>
                </thead>

                <tbody>

                    <?php if (isset($this->dados) && !empty($this->dados)): ?>
                        <?php foreach ($this->dados as $dados): ?>
                            <tr>
                                <td><?php print $dados->getCurso()->getNome(); ?></td>
                                <td><?php print $dados->getModulo()->getNome(); ?></td>
                                <td><?php print $dados->getDocente()->getPessoa()->getNome(); ?></td>
                                <td><?php print "{" . $dados->getNome() . "}"; ?><a href="<?php print URL . $dados->getNome(); ?>" target="_BLANK">     (VER)</a></td>
                                <td><?php print $dados->getData(); ?></td>
                            </tr>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </tbody>
            </table>

        </div>
    </div>
</div>

