<?php echo $this->menu; ?>
<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">
    <div class="navbar">
        <h3></h3>
        <h3></h3>
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "relatorio" . DS1 . "graficoGeral/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Grafico</span></a></li>
            <li class="active"><a href="<?php echo URL . "relatorio" . DS1 . "aproveitamentoGrafico/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Por Aproveitamento</span></a></li>
        </ul>
    </div>
</div>

<div class="span10 " id="content" style="margin-left: 150px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>relatorio/index" id="buscar" class="form-horizontal" method="POST">
                        <fieldset>
                            <legend class="text-info text-center">Escolha uma das opções</legend>
                            <div class="control-group">
                                <label class="control-label">Opções<span class="required">*</span></label>
                                <div class="controls">
                                    <select class="span6 m-wrap " id="opcao" name="opcao">
                                        <option value="000">-Selecciona uma das opções-</option>
                                        <option value="geral">relatorio geral de alunos matriculados</option>
                                        <option value="CAP">relatorio geral de alunos matriculas no CAP</option>
                                        <option value="CEPAC">relatorio geral de alunos matriculas no CEPAC</option>
                                        <option value="CEPID">relatorio geral de alunos matriculas no CEPID</option>
                                    </select>


                                </div>
                            </div>

                        </fieldset>

                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="buscar">Gerar</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>





<?php if (isset($this->matricula) && !empty($this->matricula)): ?>
    <a  style="position: absolute; top: 400px;" href="<?php echo URL . 'relatorio/' . 'MatriculaPOrCursoImprimir/' . $this->matricula['curso']; ?>"  target="_BLANK"><h4><i class="icon icon-print"></i>Imprimir</h4></a>

    <table class="table">
        <caption class="text-center"><h4> Relatório Gerado pelo Sistema<br /><br /> TOTAL DE ALUNOS MATRICULADOS NO <?php echo $this->matricula['curso']; ?><br />

            </h4>
        </caption>

        <tbody>



            </tr>
            <tr class="ro2"><td  class="Default">
                     </td>
                <td rowspan="2"  class="ce2"><p>CURSO </p></td>
                <td colspan="2"  class="ce5"><p>GENERO</p></td>
            </tr>
            <tr class="ro2">
                <td  class="Default"> 
                </td>
                <td >
                    <p>M</p>
                </td>
                <td style="text-align:left;width:2.258cm; " >
                    <p>F</p>
                </td>
                <td><p>TOTAL</p>
                </td>
            </tr>
            <tr >

                <td></td>
                <td ><p><?php echo $this->matricula['curso']; ?></p></td>
                <td ><p><?php echo $this->matricula['h_c']; ?></p></td>
                <td ><p><?php echo $this->matricula['m_c']; ?></p>
                </td>
                <td ><p><?php echo $this->matricula['total']; ?></p>
                </td>
            </tr>


        </tbody>
    </table>
<?php endif; ?>






<?php if (isset($this->mt) && !empty($this->mt)): ?>
    <a  style="position: absolute; top: 400px;" href="<?php echo URL . 'relatorio/' . 'matriculadosImprimir/' ?>"  target="_BLANK"><h4><i class="icon icon-print"></i>Imprimir</h4></a>

    <table class="table table-striped table-bordered">
        <caption class="text-center"><h4> ESTATÍSTICA GERAL<br /><br /> TOTAL DE ALUNOS MATRICULADOS NO CEAFIE EM 2015<br />

            </h4>
        </caption>

        <tbody>



            </tr>
            <tr class="ro2"><td class="Default">
                     </td>
                <td rowspan="2"  class="ce2"><p>CURSO </p></td>
                <td colspan="2"  class="ce5"><p>GENERO</p></td>
            </tr>
            <tr class="ro2">
                <td  class="Default"> 
                </td>
                <td class="ce5"><p>M</p></td><td style="text-align:left;width:2.258cm; " class="ce5"><p>F</p>
                </td>
                <td  class="ce5"><p>TOTAL</p>
                </td>
            </tr>
            <tr >

                <td> 
                <td><p>CAP</p></td><td ><p><?php echo $this->mt['h_c']; ?></p></td>
                <td><p><?php echo $this->mt['m_c']; ?></p>
                </td>
                <td><p><?php echo $this->mt['total_cap']; ?></p>
                </td>
            </tr>

            <tr>
                <td class="Default"> 
                </td>

                <td><p>CEPAC</p></td>
                <td ><p><?php echo $this->mt['h_cepac']; ?></p>
                </td>
                <td><p><?php echo $this->mt['m_cepac']; ?></p></td>
                <td><p><?php echo $this->mt['total_cepac']; ?></p>
                </td>
                <td> 
                </td>
            </tr>
            <tr>
                <td class="Default"> 
                </td>


                <td><p>CEPID </p>
                </td><td  class="ce3"><p><?php echo $this->mt['h_cepid']; ?></p>
                </td><td class="ce3"><p><?php echo $this->mt['m_cepid']; ?></p>
                </td><td  class="ce5"><p><?php echo $this->mt['total_cepid']; ?></p>
                </td>

            <tr>
                <td class="Default"> 
                </td>

                <td  class="ce3"><p>TOTAL </p>
                </td><td class="ce3"><p><?php echo $this->mt['total_h']; ?></p>
                </td><td  class="ce3"><p><?php echo $this->mt['total_m']; ?></p>
                </td><td class="ce5"><p><?php echo $this->mt['total_geral']; ?></p>
                </td>

        </tbody>
    </table>

<?php endif; ?>

