<?php echo $this->menu; ?>
<?php

function selected($value, $selected) {
    return $value == $selected ? ' selected="selected"' : '';
}
?>

<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">

    <h3></h3>
    <div class="navbar">
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "index/" ?>" class="btn btn-primary"><span style="font-size: 14px; color:  #ffffff;" >Ver Alunos</span></a></li>
            <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "editar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #ffffff;">Editar</span></a></li>
            <li class="active"><a href="<?php echo URL . "matricula" . DS1 . "remover/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #ffffff;">Apagar</span></a></li>
        </ul>
    </div>


</div>



    <div class="span10 " id="content" style="margin-left: 150px;">
        <!-- validation -->
        <div class="row-fluid">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header" style="margin-top: 20px;">
                    <div class="muted pull-right" style="padding: 10px; float: left; color: blue;">Dados do Aluno</div>
                </div>
                <div class="block-content collapse in">
                    <div class="span12">
                        <!-- BEGIN FORM-->
                        <form action="" id="adicionar" class="form-horizontal" method="POST" >
                            <fieldset>
                                <legend>Dados Pessoas</legend>
                                <?php if (isset($this->dados) && !empty($this->dados)): ?>


                                    <div class="control-group">
                                        <label class="control-label">Nome<span class="required">*</span></label>
                                        <div class="controls">
                                            <input type="text" name="nome" data-required="1" class="span6 m-wrap" value="<?php print $this->dados->getAluno()->getPessoa()->getNome(); ?>"/>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label">Genero<span class="required">*</span></label>
                                        <div class="controls">
                                            <select class="span6 m-wrap" name="genero">
                                                <option value="Masculino" <?php echo selected($this->dados->getAluno()->getPessoa()->getGenero(), "Masculino") ?> >Masculino</option>
                                                <option value="Femenino" <?php echo selected($this->dados->getAluno()->getPessoa()->getGenero(), "Femenino") ?> >Femenino</option>

                                            </select>                                    
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label">Nª Bi<span class="required">*</span></label>
                                        <div class="controls">
                                            <input name="bi" type="text" class="span6 m-wrap" value="<?php print $this->dados->getAluno()->getPessoa()->getBi(); ?>"/>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label">Nacionalidade<span class="required">*</span></label>
                                        <div class="controls">
                                            <input name="nacionalidade" id="telefone" type="text" class="span6 m-wrap" value="<?php print $this->dados->getAluno()->getPessoa()->getNacionalidade(); ?>"/>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label">Telefone<span class="required">*</span></label>
                                        <div class="controls">
                                            <input name="telefone" type="tel" class="span6 m-wrap" value="<?php print $this->dados->getAluno()->getPessoa()->getTelefone(); ?>"/>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label">Email<span class="required">*</span></label>
                                        <div class="controls">
                                            <input name="email"  class="span6 m-wrap" type="email" value="<?php print $this->dados->getAluno()->getPessoa()->getEmail(); ?>"/>
                                        </div>
                                    </div>



                                    <fieldset>
                                        <legend>Dados Académicos</legend>
                                        <div class="control-group">
                                            <label class="control-label">graduação<span class="required">*</span></label>
                                            <div class="controls">
                                                <input type="text" name="graduacao" data-required="1" class="span6 m-wrap" value="<?php print $this->dados->getAluno()->getGraduacao(); ?>"/>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label">Universidade<span class="required">*</span></label>
                                            <div class="controls">
                                                <input name="universidade" type="text" class="span6 m-wrap" value="<?php print $this->dados->getAluno()->getUniversidade(); ?>"/>
                                            </div>
                                        </div>
                                    </fieldset>

                                    <fieldset>
                                        <legend>Dados Profissionais</legend>
                                        <div class="control-group">
                                            <label class="control-label">Unidade Organica<span class="required">*</span></label>
                                            <div class="controls">
                                                <input type="text" name="unidade_organica" data-required="1" class="span6 m-wrap" value="<?php print $this->dados->getAluno()->getUnidadeOrganica(); ?>"/>
                                            </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label">Categoria Docente<span class="required">*</span></label>
                                            <div class="controls">
                                                <select class="span6 m-wrap" name="categoria_docente">
                                                    <option value="Assistente" <?php echo selected($this->dados->getAluno()->getCategoriaDocente(), "Assistente") ?>>Assistente</option>
                                                    <option value="Associado" <?php echo selected($this->dados->getAluno()->getCategoriaDocente(), "Associado") ?> >Associado</option>
                                                    <option value="Titular" <?php echo selected($this->dados->getAluno()->getCategoriaDocente(), "Titular") ?>>Titular</option>
                                                    <option value="Nenhum" <?php echo selected($this->dados->getAluno()->getCategoriaDocente(), "Nenhum") ?>>Nenhum</option>
                                                </select>
                                            </div>
                                        </div>
                                        <br />

                                        <div class="control-group">
                                            <label class="control-label">Função<span class="required">*</span></label>
                                            <div class="controls">
                                                <select class="span6 m-wrap" name="funcao">
                                                    <option value="Chefe de departamento" <?php echo selected($this->dados->getAluno()->getFuncao(), "Chefe de departamento") ?>>Chefe de departamento</option>
                                                    <option value="Chefe de seccao" <?php echo selected($this->dados->getAluno()->getFuncao(), "Chefe de seccao") ?>>Chefe de seccao</option>
                                                    <option value="Tecnica" <?php echo selected($this->dados->getAluno()->getFuncao(), "Tecnica") ?>>Tecnica</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="control-group">
                                            <label class="control-label">Categoria Cientifica<span class="required">*</span></label>
                                            <div class="controls">
                                                <select class="span6 m-wrap" name="categoria_centifica">
                                                    <option value="Investigador" <?php echo selected($this->dados->getAluno()->getCategoriaCientifica(), "Investigador") ?>>Investigador</option>
                                                    <option value="Nenhuma" <?php echo selected($this->dados->getAluno()->getCategoriaCientifica(), "Nenhuma") ?>>Nenhuma</option>
                                                </select>  
                                            </div>
                                        </div>

                                    </fieldset>



                                    <input name="enviar" type="hidden" value="1"/>
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                                        <button type="reset" class="btn">Cancelar</button>
                                    </div>
                                </fieldset>
                                <?php
                            endif;
                            ?>
                        </form>

                        <!-- END FORM-->
                    </div>
                </div>
            </div>
            <!-- /block -->
        </div>
        <!-- /validation -->

    </div>

</form>
<!-- END FORM-->
</div>
</div>
</div>
<!-- /block -->
</div>
<!-- /validation -->

</div>
</div>