<style>
    .login-dialog {
        width: 650px;
    }
</style>

<div class="container alert_info">    
    <div class="row" style="text-align:center; border-bottom:1px dashed #ccc;  padding:0 0 20px 0; margin-bottom:30px;">
        <br /><br /><br />
        <h3 style="font-family:arial; font-weight:bold; font-size:30px; padding-left: 30px;" class="text-left">
            Ficha do Aluno
        </h3>

    </div>

    <?php if (isset($this->dados) && !empty($this->dados)): ?>

        <ul class="nav navbar-nav">
            <?php if (!empty($this->dados->getAluno()->getPessoa()->getImagem())) : ?>
                <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                    <img src="<?php print URL . DS1; ?><?php echo $this->dados->getAluno()->getPessoa()->getImagem(); ?>" class="img-responsive" alt="Imagem do Aluno">
                </li>
            <?php else: ?>
                <li>
                <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                    <img src="<?php print URL; ?>public/img/10.jpg" class="img-responsive" alt="Imagem do Aluno">
                    <p>Descrição: imagem(largura:348,altura:348)</p>
                </li>
                <form id="guarda" method="POST" action="<?php print URL . "matricula/editarImagem/" . $this->dados->getAluno()->getPessoa()->getId() ?>" accept-charset="utf-8" enctype="multipart/form-data">
                    <input type="file" name="imagem" />
                    <input type="hidden" name="id" value="<?php echo $this->dados->getAluno()->getId(); ?>" />
                    <input type="submit" value="Guardar" id="guarda" class="btn btn-primary"/>
                </form>

            <?php endif; ?>
        </ul>             
    </div> 

    <div style="margin-left: 300px; margin-top: -300px;">

        <span class="text-center">

            <h4>Nome: <?php echo ucfirst($this->dados->getAluno()->getPessoa()->getNome()); ?></h4>
            <h4>BI: <?php echo $this->dados->getAluno()->getPessoa()->getBi(); ?></h4>
            <h4>Genero: <?php echo ucfirst($this->dados->getAluno()->getPessoa()->getGenero()); ?></h4>
            <h4>Email: <?php echo $this->dados->getAluno()->getPessoa()->getEmail(); ?></h4>
            <h4>Telefone: <?php echo $this->dados->getAluno()->getPessoa()->getTelefone(); ?></h4>
            <h4>Nacionalidade: <?php echo ucfirst($this->dados->getAluno()->getPessoa()->getNacionalidade()); ?></h4>
            <h4>Matricula: <?php echo date('d/m/Y', strtotime($this->dados->getData())); ?></h4>
            <hr>
        </span> 
        <br />
        <hr>
    </div>
    <span class="text-left">
        <?php if (isset($this->modulo) && !empty($this->modulo)): ?>


            <table  class="table table-striped table-bordered" >   
                <thead>

                    <tr>

                        <th>Curso</th> 
                        <th>Modulo</th>
                        <th>Data</th>


                    </tr>
                </thead>

                <tbody>

                    <?php foreach ($this->modulo as $valor): ?>

                        <tr>

                            <td>
                                <?php echo $valor->getModulo()->getCurso()->getNome(); ?>


                            </td>

                            <td>
                                <?php echo $valor->getModulo()->getNome(); ?>
                            </td>

                            <td>
                                <?php echo $valor->getData(); ?> 
                            </td>
                        <?php endforeach; ?>
                    </tr>
                </tbody>
            </table>

            <?php
        endif;
        ?>


    </span>




<?php else: ?>
    <span class="text-center">

        <h2>SEM INFORMAÇÕES PARA MOSTRAR</h2>

        <hr>
    </span> 

<?php endif; ?>

