<?php echo $this->menu; ?>
<div class="" id="content" style="margin-left: 8px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">

            <div class="col-12 pull-left" style="margin-left: 20px; margin-top:   -90px; display: block;">
                <!--<h4>Adicionar Novo</h4>-->
                <div class="navbar">
                    <ul class="nav navbar-nav">
                        <li class="active click"><a href="<?php echo URL . "usuario" . DS1 . "adicionar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Novo</span></a></li>
                      </ul>
                </div>


            </div>

            <div class="block-content collapse in" style="margin-top:1px;">
                <div class="span12">

                    <table  class="table table-striped table-bordered" id="tabela">   
                        <thead>
                            <tr class="odd gradeA">
                                <th>Nome</th> 
                                <th>Login</th>
                                <th>Nivel</th>
                                <th>Alterar</th>
                                <th>Apagar</th>
                            </tr>
                        </thead>

                        <tbody>
                            <?php if (isset($this->usuarios) && !empty($this->usuarios)): ?>
                                <?php foreach ($this->usuarios as $dados): ?>

                                    <tr>
                                        <td><?php print $dados->getPessoa()->getNome(); ?></td>
                                        <td><?php print $dados->getLogin(); ?></td>
                                        <td><?php print $dados->getNivel(); ?></td>
                                        <td><a rel="<?php print URL . "usuario/editar/" . $dados->getId(); ?>" href="<?php print URL . "usuario/editar/" . $dados->getId(); ?>" id="usuario1"><i class="icon-pencil"></i></a></td>
                                        <td><a rel="<?php print URL . "usuario" . DS1 . "remover" . DS1 . $dados->getPessoa()->getId(); ?>" href="<?php print URL . "usuario" . DS1 . "remover" . DS1 . $dados->getPessoa()->getId(); ?>" id="remover"><i class="icon-trash"></i></a></td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    <?php else: ?>
                        <h2 class="text-center text-error">Nenhum usuario cadastrado</h2>
                    <?php endif; ?>
                    <?php if (isset($this->paginacao) && !empty($this->paginacao)) //echo $this->paginacao;       ?>
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
</div>