<?php echo $this->menu;?>
<div class="span10 " id="content" style="margin-left: 150px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header" style="margin-top: 20px;">
                <div class="muted pull-right" style="padding: 10px; float: left; color: blue;">Dados do Aluno</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>curso/editar" id="editar" class="form-horizontal" method="POST">
                        <fieldset>
                            <legend>Dados Pessoas</legend>
                            <?php if (isset($this->dados) && !empty($this->dados)): ?>
                                <div class="control-group">
                                    <label class="control-label">Nome<span class="required">*</span></label>
                                    <div class="controls">
                                        <input type="text" name="nome" data-required="1" class="span6 m-wrap" value="<?php echo $this->dados->getNome(); ?>"/>
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label">Descrição<span class="required">*</span></label>
                                    <div class="controls">
                                        <textarea name="descricao"  class="span6 m-wrap"><?php echo $this->dados->getDescricao(); ?></textarea>
                                    </div>
                                </div>
                            </fieldset>

                            <input name="enviar" type="hidden" value="1"/>
                            <input name="id" type="hidden" value="<?php echo $this->dados->getId(); ?>"/>                     
                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary" id="editar">Salvar Dados</button>
                                <button type="reset" class="btn">Cancelar</button>
                            </div>
                        <?php endif; ?>
                        </fieldset>
                    </form>

                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>






























</form>
<!-- END FORM-->
</div>
</div>
</div>
<!-- /block -->
</div>
<!-- /validation -->

</div>
</div>