<?php echo $this->menu; ?>

<div class="col-12 pull-left" style="position: absolute; top: -10px; left: 10px;">
    <h3></h3>
    <h3></h3>
    <div class="navbar">
        <ul class="nav navbar-nav">
            <li class="active"><a href="<?php echo URL . "curso" . DS1 . "index/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Ver</span></a></li>
            <li class="active"><a href="<?php echo URL . "curso" . DS1 . "editar/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Editar</span></a></li>
            <li class="active"><a href="<?php echo URL . "curso" . DS1 . "remover/" ?>" class="btn btn-primary"><span style="font-size: 14px; color: #FFFFFF;">Apagar</span></a></li>
        </ul>
    </div>


</div>

<div class="span10 " id="content" style="margin-left: 150px;">
    <!-- validation -->
    <div class="row-fluid">
        <!-- block -->
        <div class="block">



            <div class="navbar navbar-inner block-header" style="margin-top: 20px;">
                <div class="muted pull-right" style="padding: 10px; float: left; color: blue;">Dados do Curso</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <!-- BEGIN FORM-->
                    <form action="<?php print URL; ?>curso/adicionar" id="adicionar" class="form-horizontal" method="POST" enctype="multipart/form-data">
                        <fieldset>
                            <legend>Dados do Curso</legend>
                            <div class="control-group">
                                <label class="control-label">Nome<span class="required">*</span></label>
                                <div class="controls">
                                    <input type="text" name="nome" data-required="1" class="span6 m-wrap"/>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Descrição<span class="required">*</span></label>
                                <div class="controls">
                                    <textarea name="descricao"  class="span6 m-wrap"></textarea>
                                </div>
                            </div>
                        </fieldset>

                        <input name="enviar" type="hidden" value="1"/>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="adicionar">Salvar Dados</button>
                            <button type="reset" class="btn">Cancelar</button>
                        </div>
                        </fieldset>
                    </form>

                    <!-- END FORM-->
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
    <!-- /validation -->

</div>






























</form>
<!-- END FORM-->
</div>
</div>
</div>
<!-- /block -->
</div>
<!-- /validation -->

</div>
</div>